In [15]:
import numpy as np
from sklearn.preprocessing import OrdinalEncoder

In [16]:
data = np.array([['low'],['medium'],['high'],['low'],['high']])
data

array([['low'],
       ['medium'],
       ['high'],
       ['low'],
       ['high']], dtype='<U6')

In [17]:
OE = OrdinalEncoder(categories=[['low','medium','high']], dtype=int)

In [18]:
OE.fit_transform(data)

array([[0],
       [1],
       [2],
       [0],
       [2]])

One Hot Encoding
onehotencoder class

In [19]:
data = np.array([['Apple'],['Orange'],['Banana']])

In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
OHE= OneHotEncoder(sparse_output=False,dtype=int)

In [22]:
OHE.fit_transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

Pandas

In [16]:
import pandas as pd

In [17]:
df = pd.DataFrame({'Color':['Black','Blue','Red','Orange'],
                   'sr no':[1,2,3,4]})
df

    Color  sr no
0   Black      1
1    Blue      2
2     Red      3
3  Orange      4

In [20]:
df = pd.get_dummies(df,dtype=int)
df

   sr no  Color_Black  Color_Blue  Color_Orange  Color_Red
0      1            1           0             0          0
1      2            0           1             0          0
2      3            0           0             0          1
3      4            0           0             1          0

Label Encoding

for converting nominal data into orders

In [31]:
colors = ['Black','Blue','Green','Red','Orange']

In [32]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le = LabelEncoder()

In [34]:
le. fit_transform(colors) # alphabaticals ordes

array([0, 1, 2, 4, 3])